many additions
Signed-off-by: Eric Lin <eric.lin@consensys.net>

diff --git a/.github/workflows/case.yml b/.github/workflows/case.yml
--- a/.github/workflows/case.yml
+++ b/.github/workflows/case.yml
@@ -3,6 +3,12 @@ name: Check file name case
 
 on: [pull_request]
 
+inputs:
+  DOC_DIR:
+    description: "doc directory path from project root"
+    required: false
+    default: docs
+
 jobs:
   lint:
     name: Check file name case
@@ -11,5 +17,20 @@ jobs:
       contents: read
     steps:
       - uses: actions/checkout@v3
-      - name: Check file name case
-        uses: ConsenSys/doctools.action-builder/actions/tests/case@main
+      - name: Check pages file name case
+        shell: sh
+        run: |
+          echo "Testing file case in ${{ inputs.DOC_DIR }}."
+          passed=true
+          for filename in `find ${{ inputs.DOC_DIR }} -name "*.md" | ( ! grep -P -v "^[[:lower:][:digit:]\/\-_]+\.md$" )`
+          do
+            echo "$filename"
+            echo "::error file=$filename ::File path must be only lowercase letters, digits, - (dash) and _ (underscore)"
+            passed=false
+          done;
+          if [ "$passed" = false ] ; then
+            echo "::error ::Some files path are incorrect. Check error annotations in the pull request."
+            echo "Correct example: my-folder/my-file-name_new2.md"
+            echo "Wrong example: My-Folder/MyFile-NAME.old.md"
+            exit 1
+          fi
